[package]
name = "rust_relm_examples"
version = "0.1.0"
authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2018"

[[bin]]
name = "first_app"
path = "src/first_app/main.rs"

[dependencies]
gtk = "0.15.5"
relm = "0.23.0"
relm-derive = "0.23.0"
